accept ssh diffie-hellman-group1-sha1 and update cert-manager
openssh-client, etc. updated and might not accept these algos by
default. Cirros images should probably be updated at some point to
use a new SSH server.

Update cert-manager to 1.8.0 because [1] changed `deploy-k8s.sh`
to use Kubernetes 1.23 instead of 1.19.

This broke cert-manager as ca-injector had an error of:

Error: error registering secret controller: no matches for kind
"MutatingWebhookConfiguration" in version
"admissionregistration.k8s.io/v1beta1"

This is because admissionregistration.k8s.io/v1beta1 no longer exists
in Kubernetes 1.23.

Upgrade cert-manager so it uses admissionregistration.k8s.io/v1 instead.

1 - https://review.opendev.org/c/openstack/openstack-helm-infra/+/840691

Change-Id: I5ea204bbcd7add2f787df79ac1d996842f4d1fcc