glance-api+neutron-server: add raise_for_status method call to livenessProbe
Without it, the livenessProbe will accept error return codes (4xx, 5xx).
In our case it was causing problems in glance-api and this fix solved the
condition where glance-api, e.g. in cases of controller node restarts
during maintenance, raised this error:

socket.gaierror: [Errno -3] Temporary failure in name resolution

and glace-api container didn't work since then correctly, showing this:

"--- no python application found, check your startup logs for errors ---"

As for neutron-server, I haven't seen the same issue yet but as the
probe's command is the same as for glance-api the fix applies as well.

I tested both glance-api and neutron-server - they works fine with this
fix.

Change-Id: Ia9663a74a3fcdfe676362bc6bd7b72e69156cbb8
Signed-off-by: Ales Rothbauer <ales.rothbauer@prozeta.eu>