Fix 'tox -e releasenotes'
Running 'tox -e releasenotes' fails with:

ERROR: You must give at least one requirement to install

Added missing doc/requirements.txt dep to tox.ini, similar
to recent openstack-helm patch.

Trivialfix

Change-Id: I01f82cdd92828ad0c99c343a1261f57562be3041